resolutions = [256]

[[directory]]
path = '/inspire/hdd/project/chineseculture/public/yuxuan/datasets/cc12m-merged/group_000'
num_repeats = 1

[[directory]]
path = '/inspire/hdd/project/chineseculture/public/yuxuan/datasets/cc12m-merged/group_001'
num_repeats = 1

[[directory]]
path = '/inspire/hdd/project/chineseculture/public/yuxuan/datasets/cc12m-merged/group_002'
num_repeats = 1

[[directory]]
path = '/inspire/hdd/project/chineseculture/public/yuxuan/datasets/cc12m-merged/group_003'
num_repeats = 1

[[directory]]
path = '/inspire/hdd/project/chineseculture/public/yuxuan/datasets/cc12m-merged/group_004'
num_repeats = 1

[[directory]]
path = '/inspire/hdd/project/chineseculture/public/yuxuan/datasets/cc12m-merged/group_005'
num_repeats = 1

[[directory]]
path = '/inspire/hdd/project/chineseculture/public/yuxuan/datasets/cc12m-merged/group_006'
num_repeats = 1

[[directory]]
path = '/inspire/hdd/project/chineseculture/public/yuxuan/datasets/cc12m-merged/group_007'
num_repeats = 1

[[directory]]
path = '/inspire/hdd/project/chineseculture/public/yuxuan/datasets/cc12m-merged/group_008'
num_repeats = 1

[[directory]]
path = '/inspire/hdd/project/chineseculture/public/yuxuan/datasets/cc12m-merged/group_009'
num_repeats = 1

[[directory]]
path = '/inspire/hdd/project/chineseculture/public/yuxuan/datasets/cc12m-merged/group_010'
num_repeats = 1

[[directory]]
path = '/inspire/hdd/project/chineseculture/public/yuxuan/datasets/cc12m-merged/group_011'
num_repeats = 1

[[directory]]
path = '/inspire/hdd/project/chineseculture/public/yuxuan/datasets/cc12m-merged/group_012'
num_repeats = 1

[[directory]]
path = '/inspire/hdd/project/chineseculture/public/yuxuan/datasets/cc12m-merged/group_013'
num_repeats = 1

[[directory]]
path = '/inspire/hdd/project/chineseculture/public/yuxuan/datasets/cc12m-merged/group_014'
num_repeats = 1

[[directory]]
path = '/inspire/hdd/project/chineseculture/public/yuxuan/datasets/cc12m-merged/group_015'
num_repeats = 1

[[directory]]
path = '/inspire/hdd/project/chineseculture/public/yuxuan/datasets/cc12m-merged/group_016'
num_repeats = 1

[[directory]]
path = '/inspire/hdd/project/chineseculture/public/yuxuan/datasets/cc12m-merged/group_017'
num_repeats = 1

[[directory]]
path = '/inspire/hdd/project/chineseculture/public/yuxuan/datasets/cc12m-merged/group_018'
num_repeats = 1

[[directory]]
path = '/inspire/hdd/project/chineseculture/public/yuxuan/datasets/cc12m-merged/group_019'
num_repeats = 1

[[directory]]
path = '/inspire/hdd/project/chineseculture/public/yuxuan/datasets/cc12m-merged/group_020'
num_repeats = 1

[[directory]]
path = '/inspire/hdd/project/chineseculture/public/yuxuan/datasets/cc12m-merged/group_021'
num_repeats = 1

[[directory]]
path = '/inspire/hdd/project/chineseculture/public/yuxuan/datasets/cc12m-merged/group_022'
num_repeats = 1

[[directory]]
path = '/inspire/hdd/project/chineseculture/public/yuxuan/datasets/cc12m-merged/group_023'
num_repeats = 1
