resolutions = [256]



[[directory]]
path = '/inspire/hdd/project/chineseculture/public/yuxuan/datasets/cc12m-unpacked/cc12m-train-0648'
num_repeats = 1



[[directory]]
path = '/inspire/hdd/project/chineseculture/public/yuxuan/datasets/cc12m-unpacked/cc12m-train-0649'
num_repeats = 1
