
resolutions = [256]


[[directory]]
path = '/inspire/hdd/project/chineseculture/public/yuxuan/datasets/cc12m-merged/group_000'
num_repeats = 1

[[directory]]
path = '/inspire/hdd/project/chineseculture/public/yuxuan/datasets/cc12m-merged/group_001'
num_repeats = 1

[[directory]]
path = '/inspire/hdd/project/chineseculture/public/yuxuan/datasets/cc12m-merged/group_002'
num_repeats = 1


